### ISSUE TITLE
Abilities should be split into AoE, Targeted, and Self

### ISSUE THREAD

**Issue by darthvadrismydad** [lexwebb/MCMOBA#1]
From what I can see right now, there are going to be 3 different kinds of "abilities". Another ability modifier I could think of is the state of "active" or "passive".

I will create a quick mock-up of interfaces so that you can see how I would go about splitting up the Ability classes methods. This will be given in the form of a pull request. @lexwebb

**Comment by lexwebb** [comment]
Sounds good. I initially planned similar but due to the many different natures of abilities I have planned it all got a bit confusing!

**Comment by lexwebb** [comment]
You online? Ignore this if you get it an hour after i sent it :)

**Comment by darthvadrismydad** [comment]
Yeah I'm online. whats up?

**Comment by lexwebb** [comment]
Just having a few problems with my new ability and things ive done before not working :) Also wondering hwo to implement your additions

**Comment by darthvadrismydad** [comment]
Ah ok. do you have your teamspeak server up? I can get on that. Or Saros?

**Comment by lexwebb** [comment]
Yeah. voip2.roxservers.com:10003
