### ISSUE TITLE
Abilities should have a "State"

### ISSUE THREAD

**Issue by darthvadrismydad** [lexwebb/MCMOBA#2]
For the "State" of an ability, when thinking about it, abilities could potentially oscillate between different states, depending on whether or not they are on cooldown.

So there could be a certain set of benefits (as in faster movement, more strength, higher jumping, faster health regen) or detriments (slower movement, lower defence, constant health loss).

Defining both "Active" and "Passive" here:

Active: When an Ability has been activated or is on cooldown.
Passive: When an Ability is not activated.
@lexwebb

**Comment by lexwebb** [comment]
This would definatley be a good feature!
